P8105_HW2_HL2710
================
Ainsel Levitskaia-Collins, HL2710
2025-09-25

### Problem 1

Importing and cleaning `pols_month`:

- Breaking `mon` into year/month/day variables
- Replacing month number with month name
- Combining `prez_dem` and `prez_gop` into a single variable
- Removing the`day` variable
- Ensure that the `year` variable will match with the `snp` dataset

``` r
pols_month <-
  read_csv("./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "mon"), sep = 4) %>% 
  separate(mon, into = c("month", "day"), sep = 4) %>% 
  mutate(
    month = case_match(month,
      "-01-" ~ "January",
      "-02-" ~ "February",
      "-03-" ~ "March",
      "-04-" ~ "April",
      "-05-" ~ "May",
      "-06-" ~ "June",
      "-07-" ~ "July",
      "-08-" ~ "August",
      "-09-" ~ "September",
      "-10-" ~ "October",
      "-11-" ~ "November",
      "-12-" ~ "December")) %>% 
  pivot_longer(
    starts_with("prez_"), 
    names_to = "president", 
    names_prefix = "prez_", 
    values_to = "president_yn") %>% 
  separate(year, into = c("extra", "year"), sep = 2) %>% 
  select(-day, -extra)

pols_month
```

    ## # A tibble: 1,644 × 10
    ##    year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 47    January       23      51     253      23      45     198 gop      
    ##  2 47    January       23      51     253      23      45     198 dem      
    ##  3 47    February      23      51     253      23      45     198 gop      
    ##  4 47    February      23      51     253      23      45     198 dem      
    ##  5 47    March         23      51     253      23      45     198 gop      
    ##  6 47    March         23      51     253      23      45     198 dem      
    ##  7 47    April         23      51     253      23      45     198 gop      
    ##  8 47    April         23      51     253      23      45     198 dem      
    ##  9 47    May           23      51     253      23      45     198 gop      
    ## 10 47    May           23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows
    ## # ℹ 1 more variable: president_yn <dbl>

Importing and cleaning `snp`:

- Breaking `date` into year/month/day variables
- Ensuring that `year` and `month` are the leading columns
- Removing the `day` variable
- Replacing month number with month name

``` r
snp <-
  read_csv("./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate_wider_delim(
    date,
    delim = "/",
    names_sep = ".") %>% 
  select(
    year = date.3,
    month = date.1,
    everything()
  ) %>% 
  select(-date.2) %>% 
  mutate(
    month = case_match(month,
      "1" ~ "January",
      "2" ~ "February",
      "3" ~ "March",
      "4" ~ "April",
      "5" ~ "May",
      "6" ~ "June",
      "7" ~ "July",
      "8" ~ "August",
      "9" ~ "September",
      "10" ~ "October",
      "11" ~ "November",
      "12" ~ "December"))

snp
```

    ## # A tibble: 787 × 3
    ##    year  month    close
    ##    <chr> <chr>    <dbl>
    ##  1 15    July     2080.
    ##  2 15    June     2063.
    ##  3 15    May      2107.
    ##  4 15    April    2086.
    ##  5 15    March    2068.
    ##  6 15    February 2104.
    ##  7 15    January  1995.
    ##  8 14    December 2059.
    ##  9 14    November 2068.
    ## 10 14    October  2018.
    ## # ℹ 777 more rows

Importing and cleaning `unemployment`:

- Switching from “wide” to “long” format
- Ensuring all variables have the appropriate name
- Ensuring that all variables take the same values
- Ensure that the `year` variable will match with the `snp` dataset

``` r
unemployment <-
  read_csv("./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "prcnt_unemployment"
  ) %>% 
  mutate(
    month = case_match(month,
      "jan" ~ "January",
      "feb" ~ "February",
      "mar" ~ "March",
      "apr" ~ "April",
      "may" ~ "May",
      "jun" ~ "June",
      "jul" ~ "July",
      "aug" ~ "August",
      "sep" ~ "September",
      "oct" ~ "October",
      "nov" ~ "November",
      "dec" ~ "December")) %>% 
  separate(year, into = c("extra", "year"), sep = 2) %>% 
  select(-extra)

unemployment
```

    ## # A tibble: 816 × 3
    ##    year  month     prcnt_unemployment
    ##    <chr> <chr>                  <dbl>
    ##  1 48    January                  3.4
    ##  2 48    February                 3.8
    ##  3 48    March                    4  
    ##  4 48    April                    3.9
    ##  5 48    May                      3.5
    ##  6 48    June                     3.6
    ##  7 48    July                     3.6
    ##  8 48    August                   3.9
    ##  9 48    September                3.8
    ## 10 48    October                  3.7
    ## # ℹ 806 more rows

Joining datasets:

1.  Merge `snp` into `pols`
2.  Merge `unemployment` into the result

``` r
pols_snp_unemployment <- left_join(pols_month, snp, by = c("year", "month")) %>% 
  left_join(unemployment, by = c("year", "month"))

pols_snp_unemployment
```

    ## # A tibble: 1,644 × 12
    ##    year  month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <chr> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1 47    January       23      51     253      23      45     198 gop      
    ##  2 47    January       23      51     253      23      45     198 dem      
    ##  3 47    February      23      51     253      23      45     198 gop      
    ##  4 47    February      23      51     253      23      45     198 dem      
    ##  5 47    March         23      51     253      23      45     198 gop      
    ##  6 47    March         23      51     253      23      45     198 dem      
    ##  7 47    April         23      51     253      23      45     198 gop      
    ##  8 47    April         23      51     253      23      45     198 dem      
    ##  9 47    May           23      51     253      23      45     198 gop      
    ## 10 47    May           23      51     253      23      45     198 dem      
    ## # ℹ 1,634 more rows
    ## # ℹ 3 more variables: president_yn <dbl>, close <dbl>, prcnt_unemployment <dbl>

The `pols_month` dataset has 1644 observations and 10 variables, and it
contains information on the number of republican and democratic
governors, senators, and representatives, and whether the president is
democratic and republican, for each observed date. The `snp` dataset has
787 observations and 3 variables, and it contains information on the
closing value of the S&P stock index for each observed date. The
`unemployment` dataset has 816 observations and 3 variables, and it
contains information on the percentage of unemployment for each observed
date.

The final dataset resulting from a merge between the three,
`pols_snp_unemployment`, has 1644 observations and 12 variables, and it
contains the percentage of unemployment, S&P closing stock index value,
and number of politicians per political party for each observed date.

### Problem 2

Importing and cleaning `Mr. Trash Wheel`:

1.  Omit non-data entries
2.  Ensure variable names are reasonable
3.  Omit rows without dumpster-specific data
4.  Round the number of sports balls to the nearest integer and convert
    the result to an integer variable
5.  Add indicator for trash type and sort variables accordingly

``` r
mr_trash <-
  readxl::read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>% 
  select(-x15, -x16) %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls, 0),
    sports_balls = as.integer(sports_balls),
    trash_type = "mister",
    year = as.numeric(year)
  ) %>% 
  select(dumpster, trash_type, everything())

mr_trash
```

    ## # A tibble: 651 × 15
    ##    dumpster trash_type month  year date                weight_tons
    ##       <dbl> <chr>      <chr> <dbl> <dttm>                    <dbl>
    ##  1        1 mister     May    2014 2014-05-16 00:00:00        4.31
    ##  2        2 mister     May    2014 2014-05-16 00:00:00        2.74
    ##  3        3 mister     May    2014 2014-05-16 00:00:00        3.45
    ##  4        4 mister     May    2014 2014-05-17 00:00:00        3.1 
    ##  5        5 mister     May    2014 2014-05-17 00:00:00        4.06
    ##  6        6 mister     May    2014 2014-05-20 00:00:00        2.71
    ##  7        7 mister     May    2014 2014-05-21 00:00:00        1.91
    ##  8        8 mister     May    2014 2014-05-28 00:00:00        3.7 
    ##  9        9 mister     June   2014 2014-06-05 00:00:00        2.52
    ## 10       10 mister     June   2014 2014-06-11 00:00:00        3.76
    ## # ℹ 641 more rows
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

Repeating the same process for `Professor Trash Wheel` and
`Gwynnda Trash Wheel`:

``` r
prof_trash <-
  readxl::read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(trash_type = "professor") %>% 
  select(dumpster, trash_type, everything())

prof_trash
```

    ## # A tibble: 119 × 14
    ##    dumpster trash_type month     year date                weight_tons
    ##       <dbl> <chr>      <chr>    <dbl> <dttm>                    <dbl>
    ##  1        1 professor  January   2017 2017-01-02 00:00:00        1.79
    ##  2        2 professor  January   2017 2017-01-30 00:00:00        1.58
    ##  3        3 professor  February  2017 2017-02-26 00:00:00        2.32
    ##  4        4 professor  February  2017 2017-02-26 00:00:00        3.72
    ##  5        5 professor  February  2017 2017-02-28 00:00:00        1.45
    ##  6        6 professor  March     2017 2017-03-30 00:00:00        1.71
    ##  7        7 professor  April     2017 2017-04-01 00:00:00        1.82
    ##  8        8 professor  April     2017 2017-04-20 00:00:00        2.37
    ##  9        9 professor  May       2017 2017-05-10 00:00:00        2.64
    ## 10       10 professor  May       2017 2017-05-26 00:00:00        2.78
    ## # ℹ 109 more rows
    ## # ℹ 8 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, homes_powered <dbl>

``` r
gwynnda_trash <-
  readxl::read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(trash_type = "gwynnda") %>% 
  select(dumpster, trash_type, everything())

gwynnda_trash
```

    ## # A tibble: 263 × 13
    ##    dumpster trash_type month   year date                weight_tons
    ##       <dbl> <chr>      <chr>  <dbl> <dttm>                    <dbl>
    ##  1        1 gwynnda    July    2021 2021-07-03 00:00:00        0.93
    ##  2        2 gwynnda    July    2021 2021-07-07 00:00:00        2.26
    ##  3        3 gwynnda    July    2021 2021-07-07 00:00:00        1.62
    ##  4        4 gwynnda    July    2021 2021-07-16 00:00:00        1.76
    ##  5        5 gwynnda    July    2021 2021-07-30 00:00:00        1.53
    ##  6        6 gwynnda    August  2021 2021-08-11 00:00:00        2.06
    ##  7        7 gwynnda    August  2021 2021-08-14 00:00:00        1.9 
    ##  8        8 gwynnda    August  2021 2021-08-16 00:00:00        2.16
    ##  9        9 gwynnda    August  2021 2021-08-16 00:00:00        2.6 
    ## 10       10 gwynnda    August  2021 2021-08-17 00:00:00        3.21
    ## # ℹ 253 more rows
    ## # ℹ 7 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

Combining all three trash datasets to produce a single trash dataset:

``` r
trash <- left_join(
  mr_trash, prof_trash, 
  by = c("dumpster", "date", "month", "year"), 
  suffix = c(".mister", ".professor"))
```

### Problem 3
