---
title: "P8105_HW2_HL2710"
author: "Ainsel Levitskaia-Collins, HL2710"
date: "2025-09-25"
output: github_document
---

```{r include = FALSE}
library(tidyverse)
```


### Problem 1

Importing and cleaning `pols_month`:
- Breaking `mon` into year/month/day variables
- Replacing month number with month name
- Combining `prez_dem` and `prez_gop` into a single variable
- Removing the`day` variable

```{r message = FALSE}
pols_month <-
  read_csv("./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "mon"), sep = 4) %>% 
  separate(mon, into = c("month", "day"), sep = 4) %>% 
  mutate(
    month = case_match(month,
      "-01-" ~ "January",
      "-02-" ~ "February",
      "-03-" ~ "March",
      "-04-" ~ "April",
      "-05-" ~ "May",
      "-06-" ~ "June",
      "-07-" ~ "July",
      "-08-" ~ "August",
      "-09-" ~ "September",
      "-10-" ~ "October",
      "-11-" ~ "November",
      "-12-" ~ "December")) %>% 
  pivot_longer(
    starts_with("prez_"), 
    names_to = "president", 
    names_prefix = "prez_", 
    values_to = "president_yn") %>% 
  select(-day)
```


### Problem 2

### Problem 3